sudo: required

services:
  - docker

script:
  - make build test

after_success:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: michael@allen.digital
  api_key:
    secure: N3fOTLVI2KIopBcTcmFtOIo5V5QnujYZjvO5EzB4iO7hyLbstPZ+7fk77b3fjVRsarTQrYTyG7A2h55flXiG8GuEY2LDwfZANADbZNNNfP30MZIRJCvrlpIkRbhE7jPHGbRhX4OICj3I34/jqtxCVqF63Hans2HQ+1pCVQj7yDVbYfYxpaAhOfF9/7XreqygVYx4iNBKyJmB2UQnXZ3pQZxrDnlxb3l1//w0EAsEw9PBJAQjB0s5GzLmKP9C8RjR7m1vW39NyJYf2QiTlvpsH6LkSNp2Py9zFtrTACCo1fj5xJvCc7I0sYz8u3pbFCC4EpCAO3ZaXdtA97OZETLiULDUHALeuAI5H0Tz//7eFKCb6h8ZPHUiIVSLZ52VOLPkmP1DHQg2Fhnf1AzgkakTWJYPdVpG87FtJGCY3TRbgm5yEjxShSyJQsE40JQim7lVS4Edivt7XFxtTxvNuFPlyZRmI9rJ/ZLfCLlnY7cqwe+pv0desu16bLq076O5cY5Hloi8BoAIbP83HLSL9qIXdOOhetaj9gSrs40/1sVcphYJVoG4y8G/EPposxJU5WeztFF3x9FHDDhVPkMyeR6UWtL3PsukUzBIRsd6Q2yXSoM3pAnexUCyOaKUyr0uEv3FtC409RdGuK1Uz7BnMAgMaF/dCM7EWeOZ1LkPsYFScZA=
  on:
    tags: true
    repo: hmcts/tech-docs
